### PR TITLE
Updated to .NET Standard

### PR DESCRIPTION
**Pull request by MarcosCobena**
Thanks for your library :-)

### CODE REVIEW

**Comment by MarcosCobena** [comment]
Hi again,

Yesterday I run out of time and couldn't run tests on my macOS —we could move such to xUnit in a future too.

Today I confirm everything keeps working after moving to .NET Standard: all tests keep green and the solution builds just fine —did this on Windows with VS 2017.

The project's ready for building in Release and uploading a new version to NuGet, would it be possible you make such please? We'd like to consume such in

https://github.com/Microsoft/TailwindTraders-Mobile

which will for sure give some visilibity of the work you're doing :-)

Thanks again,

—Marcos

**Comment by gnaeus** [comment]
Thanks! I will publish new version tomorrow.

**Comment by MarcosCobena** [comment]
Ping, please :-)

**Comment by gnaeus** [comment]
Sorry for the long wait. I've been ill all this month =(
But now I have published a new version 0.1.5 with .NET Standard 2.0 support.

**Comment by MarcosCobena** [comment]
No problem man, I hope you find better now.

Thanks for publishing!

Take care,

—Marcos

**Pull request merged**
